class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> strings = {
    'en': {
      'money_health_score': 'Money Health Score',
      'tax_optimizer': 'Tax Optimizer',
      'fire_planner': 'FIRE Planner',
      'artha_says': 'ARTHA SAYS',
      'calculate': 'Calculate My Path',
      'critical': 'CRITICAL',
      'needs_work': 'NEEDS WORK',
      'decent': 'DECENT',
      'recommended': 'RECOMMENDED',
      'question_of': 'QUESTION {x} OF 12',
      'sent': 'SENT',
      'just_now': 'JUST NOW',
      'type_response': 'Type your response...',
      'good_morning': 'Good morning',
      'good_afternoon': 'Good afternoon',
      'good_evening': 'Good evening',
      'your_financial_mentor': 'Your Financial Mentor',
      'your_financial_architect': 'YOUR FINANCIAL ARCHITECT',
      'artha_online': 'ARTHA ONLINE',
      'fix_these_first': 'FIX THESE FIRST',
      'health_dimensions': 'HEALTH DIMENSIONS',
      'growth_projection': 'GROWTH PROJECTION',
      'asset_allocation': 'RECOMMENDED ASSET ALLOCATION',
      'artha_assessment': '✦ ARTHA ASSESSMENT',
      'simulation_params': 'SIMULATION PARAMETERS',
      'total_savings': 'TOTAL POTENTIAL SAVINGS',
      'old_regime': 'OLD REGIME',
      'new_regime': 'NEW REGIME',
      'tax_channels': 'OPTIMIZATION CHANNELS',
      'emergency_fund': 'Emergency Fund',
      'insurance': 'Insurance',
      'investment_mix': 'Investment Mix',
      'debt_health': 'Debt Health',
      'tax_efficiency': 'Tax Efficiency',
      'fire_progress': 'FIRE Progress',
      'sebi_disclaimer': 'Financial education only. Not SEBI-registered investment advice. Consult a SEBI-registered advisor before investing.',
      'loading': 'Loading...',
      'error_generic': 'Something went wrong. Please try again.',
      'offline_banner': 'No connection — showing cached data',
      'logout': 'Logout session',
      'profile': 'Profile',
      'home': 'Home',
      'health': 'Health',
      'fire': 'FIRE',
      'tax': 'Tax',
      // Dashboard
      'fire_target': 'FIRE Target',
      'tax_saving': 'Tax Saving',
      'years_left': 'years left',
      'regime': 'regime',
      'view_report': 'View report',
      // Health detail
      'artha_analysis': 'ARTHA ANALYSIS',
      'recommended_action': 'RECOMMENDED ACTION',
      // Profile
      'personal_information': 'Personal Information',
      'investment_preferences': 'Investment Preferences',
      'language': 'Language',
      'security': 'Security',
      'save_changes': 'Save Changes',
      'finiq_engine': 'FINIQ ENGINE V4.0',
    },
    'hi': {
      'money_health_score': 'धन स्वास्थ्य स्कोर',
      'tax_optimizer': 'कर अनुकूलक',
      'fire_planner': 'वित्तीय स्वतंत्रता योजना',
      'artha_says': 'अर्था कहती है',
      'calculate': 'मेरा पथ गणना करें',
      'critical': 'गंभीर',
      'needs_work': 'सुधार जरूरी',
      'decent': 'ठीक है',
      'recommended': 'अनुशंसित',
      'question_of': 'प्रश्न {x}/12',
      'sent': 'भेजा गया',
      'just_now': 'अभी',
      'type_response': 'अपनी प्रतिक्रिया टाइप करें...',
      'good_morning': 'सुप्रभात',
      'good_afternoon': 'नमस्ते',
      'good_evening': 'शुभ संध्या',
      'your_financial_mentor': 'आपका वित्तीय सलाहकार',
      'your_financial_architect': 'आपका वित्तीय सलाहकार',
      'artha_online': 'अर्था ऑनलाइन',
      'fix_these_first': 'इन्हें पहले ठीक करें',
      'health_dimensions': 'स्वास्थ्य आयाम',
      'growth_projection': 'विकास अनुमान',
      'asset_allocation': 'अनुशंसित संपत्ति आवंटन',
      'artha_assessment': '✦ अर्था का आकलन',
      'simulation_params': 'सिमुलेशन पैरामीटर',
      'total_savings': 'कुल संभावित बचत',
      'old_regime': 'पुरानी व्यवस्था',
      'new_regime': 'नई व्यवस्था',
      'tax_channels': 'अनुकूलन चैनल',
      'emergency_fund': 'आपातकालीन निधि',
      'insurance': 'बीमा',
      'investment_mix': 'निवेश मिश्रण',
      'debt_health': 'ऋण स्वास्थ्य',
      'tax_efficiency': 'कर दक्षता',
      'fire_progress': 'FIRE प्रगति',
      'sebi_disclaimer': 'केवल वित्तीय शिक्षा। SEBI-पंजीकृत निवेश सलाह नहीं। निवेश से पहले SEBI-पंजीकृत सलाहकार से परामर्श करें।',
      'loading': 'लोड हो रहा है...',
      'error_generic': 'कुछ गलत हुआ। कृपया पुनः प्रयास करें।',
      'offline_banner': 'कोई कनेक्शन नहीं — कैश डेटा दिखा रहा है',
      'logout': 'लॉगआउट',
      'profile': 'प्रोफ़ाइल',
      'home': 'होम',
      'health': 'स्वास्थ्य',
      'fire': 'FIRE',
      'tax': 'कर',
      // Dashboard
      'fire_target': 'FIRE लक्ष्य',
      'tax_saving': 'कर बचत',
      'years_left': 'साल बाकी',
      'regime': 'व्यवस्था',
      'view_report': 'रिपोर्ट देखें',
      // Health detail
      'artha_analysis': 'अर्था विश्लेषण',
      'recommended_action': 'अनुशंसित कार्रवाई',
      // Profile
      'personal_information': 'व्यक्तिगत जानकारी',
      'investment_preferences': 'निवेश प्राथमिकताएं',
      'language': 'भाषा',
      'security': 'सुरक्षा',
      'save_changes': 'परिवर्तन सहेजें',
      'finiq_engine': 'FINIQ इंजन V4.0',
    },
    'ta': {
      'money_health_score': 'பண ஆரோக்கிய மதிப்பெண்',
      'tax_optimizer': 'வரி மேம்படுத்தி',
      'fire_planner': 'நிதி சுதந்திர திட்டம்',
      'artha_says': 'அர்தா சொல்கிறார்',
      'calculate': 'என் பாதையை கணக்கிடு',
      'critical': 'மிக முக்கியம்',
      'needs_work': 'மேம்பாடு தேவை',
      'decent': 'நல்லது',
      'recommended': 'பரிந்துரைக்கப்பட்டது',
      'question_of': 'கேள்வி {x}/12',
      'sent': 'அனுப்பப்பட்டது',
      'just_now': 'இப்போது',
      'type_response': 'உங்கள் பதிலை தட்டச்சு செய்யுங்கள்...',
      'good_morning': 'காலை வணக்கம்',
      'good_afternoon': 'மதிய வணக்கம்',
      'good_evening': 'மாலை வணக்கம்',
      'your_financial_mentor': 'உங்கள் நிதி ஆலோசகர்',
      'your_financial_architect': 'உங்கள் நிதி வடிவமைப்பாளர்',
      'artha_online': 'அர்தா ஆன்லைன்',
      'fix_these_first': 'இவற்றை முதலில் சரிசெய்யுங்கள்',
      'health_dimensions': 'ஆரோக்கிய பரிமாணங்கள்',
      'growth_projection': 'வளர்ச்சி கணிப்பு',
      'asset_allocation': 'பரிந்துரைக்கப்பட்ட சொத்து ஒதுக்கீடு',
      'artha_assessment': '✦ அர்தாவின் மதிப்பீடு',
      'simulation_params': 'சிமுலேஷன் அளவுருக்கள்',
      'total_savings': 'மொத்த சாத்தியமான சேமிப்பு',
      'old_regime': 'பழைய ஆட்சி',
      'new_regime': 'புதிய ஆட்சி',
      'tax_channels': 'மேம்படுத்தல் சேனல்கள்',
      'emergency_fund': 'அவசரகால நிதி',
      'insurance': 'காப்பீடு',
      'investment_mix': 'முதலீட்டு கலவை',
      'debt_health': 'கடன் ஆரோக்கியம்',
      'tax_efficiency': 'வரி திறன்',
      'fire_progress': 'FIRE முன்னேற்றம்',
      'sebi_disclaimer': 'நிதி கல்வி மட்டுமே. SEBI-பதிவு செய்யப்பட்ட முதலீட்டு ஆலோசனை அல்ல。',
      'loading': 'ஏற்றுகிறது...',
      'error_generic': 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.',
      'offline_banner': 'இணைப்பு இல்லை — தற்காலிக தரவு காட்டுகிறது',
      'logout': 'வெளியேறு',
      'profile': 'சுயவிவரம்',
      'home': 'முகப்பு',
      'health': 'ஆரோக்கியம்',
      'fire': 'FIRE',
      'tax': 'வரி',
      // Dashboard
      'fire_target': 'FIRE இலக்கு',
      'tax_saving': 'வரி சேமிப்பு',
      'years_left': 'ஆண்டுகள் உள்ளன',
      'regime': 'ஆட்சி',
      'view_report': 'அறிக்கை பார்க்க',
      // Health detail
      'artha_analysis': 'அர்தா பகுப்பாய்வு',
      'recommended_action': 'பரிந்துரைக்கப்பட்ட நடவடிக்கை',
      // Profile
      'personal_information': 'தனிப்பட்ட தகவல்',
      'investment_preferences': 'முதலீட்டு விருப்பங்கள்',
      'language': 'மொழி',
      'security': 'பாதுகாப்பு',
      'save_changes': 'மாற்றங்களை சேமி',
      'finiq_engine': 'FINIQ என்ஜின் V4.0',
    },
  };

  static String get(String key, String lang) {
    return strings[lang]?[key] ?? strings['en']?[key] ?? key;
  }

  static String getWithParam(String key, String lang, Map<String, String> params) {
    String value = get(key, lang);
    params.forEach((k, v) {
      value = value.replaceAll('{$k}', v);
    });
    return value;
  }
}
